### PR TITLE
add aur package to README

### PR DESCRIPTION
**Pull request by stellessia**

### CODE REVIEW

**Review by AlexeyZavar — CHANGES_REQUESTED** [review]
Better "If you're using **Arch Linux** based distro, you can install `ayugram-desktop-git` package from AUR."

**Comment by stellessia** [comment]
okay, edited now

**Review by AlexeyZavar — APPROVED** [review]
lgtm for now

**Comment by AlexeyZavar** [comment]
Will merge once I get home

**Comment by ZavaruKitsu** [comment]
Added notice about AUR package at https://github.com/AyuGram/AyuGramDesktop#arch-linux

**Pull request closed without merging**
